name: skp_smartfarm
description: A farmer-friendly fertilizer management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animations
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  http: ^1.1.2
  
  # Firebase (Complete Setup)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  video_player: ^2.8.2
  chewie: ^1.7.0
  geolocator: ^11.0.0
  # Updated syncfusion_flutter_charts to a newer version compatible with intl ^0.19.0
  syncfusion_flutter_charts: ^26.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/skp_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#2E7D32"
  adaptive_icon_foreground: "assets/images/app_icon.png"
