name: skp_smartfarm
description: A farmer-friendly fertilizer management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animations
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  http: ^1.1.2
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  firebase_core: ^3.6.0
  image_picker: ^1.0.4 
  video_player: ^2.8.2
  chewie: ^1.7.0
  geolocator: ^11.0.0 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1  # ✅ Added for custom app icon

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# ✅ App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/skp_logo.png"
  min_sdk_android: 21
  
  # Adaptive icon (for Android 8.0+)
  adaptive_icon_background: "#2E7D32"  # Your green color
  adaptive_icon_foreground: "assets/images/app_icon.png"
  
  # Optional: Remove background for transparent icon
  # adaptive_icon_background: "#FFFFFF"
