name: skp_smartfarm
description: A farmer-friendly fertilizer management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  
  # UI & Animations
  flutter_animate: ^4.3.0
  lottie: ^3.0.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  http: ^1.1.2
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  flutter_local_notifications: ^16.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # Comment out assets until you have the files
  # assets:
  #   - assets/logo.png
  #   - assets/animations/
