name: skp_smartfarm
description: A farmer-friendly fertilizer management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Animations
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  http: ^1.1.2
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  firebase_core: ^3.6.0
  image_picker: ^1.0.4 
  video_player: ^2.8.2
  chewie: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

