// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcAkBomfuWYs4GoiZH7PFNefpqeWfjNWA',
    appId: '1:259424420089:web:4a81de33197cbf94116228',
    messagingSenderId: '259424420089',
    projectId: 'skp-farming',
    authDomain: 'skp-farming.firebaseapp.com',
    storageBucket: 'skp-farming.firebasestorage.app',
    measurementId: 'G-5MFG0GWW72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8l4D8AmDNqlEI_Uxe0tF1SyueyOei_CQ',
    appId: '1:259424420089:android:f149777aefff3c6a116228',
    messagingSenderId: '259424420089',
    projectId: 'skp-farming',
    storageBucket: 'skp-farming.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFEkHGNm3XS5IOpQ5uHAf0-VPRB1nj05o',
    appId: '1:259424420089:ios:58cd70001ff4b0b9116228',
    messagingSenderId: '259424420089',
    projectId: 'skp-farming',
    storageBucket: 'skp-farming.firebasestorage.app',
    iosBundleId: 'com.example.skp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcAkBomfuWYs4GoiZH7PFNefpqeWfjNWA',
    appId: '1:259424420089:web:c2a951fee8211c31116228',
    messagingSenderId: '259424420089',
    projectId: 'skp-farming',
    authDomain: 'skp-farming.firebaseapp.com',
    storageBucket: 'skp-farming.firebasestorage.app',
    measurementId: 'G-V77WX9YKLD',
  );
}
